server:
  port: 9999

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: elastic-service
  elasticsearch:
    uris: http://localhost:9200

raceapplication:
  url:
    auth: http://localhost:9090/
    user: http://localhost:9091/
    main: http://localhost:9092/