apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "2048Mi"
            cpu: "200m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "AdminSemih"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "C[?K-6)pDZe]ju`-ROi%|or8C!G1ll"
          ##quizdb 
