apiVersion: v1
kind: Secret
metadata:
  name: secretobject
type: Opaque
stringData:
  db_username: 'postgres'
  db_password: 'asdsaddas'
  db_url: 'jdbc:postgresql://10.32.1.11:5432/QuizDB'
  services_auth_clusterip: '10.36.4.88'
  services_main_clusterip: '10.36.11.35'
  services_user_clusterip: '10.36.6.49'
  auth_port: '9090'
  user_port: '9091'
  main_port: '9092'
  auth_url: 'http://10.36.4.88:9090'
  user_url: 'http://10.36.6.49:9091'
  main_url: 'http://10.36.11.35:9092'
  gateway_auth_url: 'http://10.36.4.88:9090'
  gateway_user_url: 'http://10.36.6.49:9091'
  gateway_main_url: 'http://10.36.11.35:9092'
  config_server_url: 'http://10.32.1.15:8888'
