server:
  port: 9090

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/QuizDB'
    username: 'postgres'
    password: 'asdsaddas'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/auth-service/
    user: http://localhost:9091/user-service/
    main: http://localhost:9092/main-service/