server:
  port: 9090

spring:
  security:
    user:
      name: semih
      password: 12345
  datasource:
    url: 'jdbc:postgresql://localhost:5432/QuizDB'
    username: 'postgres'
    password: 'asdsaddas'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: semih
    password: 12345
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: auth-service

raceapplication:
  url:
    auth: http://localhost:9090/
    user: http://localhost:9091/
    main: http://localhost:9092/