server:
  port: 9091

#logging:
#  level:
#    root: WARN
#    com.semih: DEBUG
#    org.springframework: INFO
#  file:
#    name: user-service-application.log

spring:
  data:
    mongodb:
      host: 146.148.69.120
      port: 19589
      database: quizdb
      username: UserSemih
      password: "asdsaddas"
  rabbitmq:
    host: localhost
    port: 5672
    username: semih
    password: 12345
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
  redis:
    host: localhost
    port: 6379
raceapplication:
  url:
    auth: http://localhost:9090/
    user: http://localhost:9091/
    main: http://localhost:9092/
