server:
  port: 9091

logging:
  level:
    root: WARN
    com.semih: DEBUG
    org.springframework: INFO
  file:
    name: user-service-application.log

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/QuizDB'
    username: 'postgres'
    password: 'asdsaddas'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/
    user: http://localhost:9091/
    main: http://localhost:9092/
